/// Flutter icons CondimentsIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CondimentsIcons
///      fonts:
///       - asset: fonts/CondimentsIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CondimentsIcons {
  CondimentsIcons._();

  static const _kFontFam = 'IngredientsIcons';
  static const _kFontPkg = null;

  static const IconData lettuce =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData onion =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cheese =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData salt =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sugar =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tomato =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nuts =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nutmeg =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
